Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PosterShop;

namespace PosterShop.Controllers
{
    public class ShopsController : Controller
    {
        private readonly PosterShopContext _context;

        public ShopsController(PosterShopContext context)
        {
            _context = context;
        }

        // GET: Shops
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shops.ToListAsync());
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shops = await _context.Shops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shops == null)
            {
                return NotFound();
            }

            return View(shops);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,Worktime")] Shops shops)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shops);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shops);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shops = await _context.Shops.FindAsync(id);
            if (shops == null)
            {
                return NotFound();
            }
            return View(shops);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Address,Worktime")] Shops shops)
        {
            if (id != shops.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shops);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopsExists(shops.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shops);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shops = await _context.Shops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shops == null)
            {
                return NotFound();
            }

            return View(shops);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shops = await _context.Shops.FindAsync(id);
            _context.Shops.Remove(shops);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopsExists(int id)
        {
            return _context.Shops.Any(e => e.Id == id);
        }
    }
}

Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PosterShop;

namespace PosterShop.Controllers
{
    public class TopicsController : Controller
    {
        private readonly PosterShopContext _context;

        public TopicsController(PosterShopContext context)
        {
            _context = context;
        }

        // GET: Topics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Topics.ToListAsync());
        }

        // GET: Topics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topics = await _context.Topics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topics == null)
            {
                return NotFound();
            }

            //return View(topics);
            return RedirectToAction("Index", "Posters", new { id = topics.Id, name = topics.Name });
        }

        // GET: Topics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Topics topics)
        {
            if (ModelState.IsValid)
            {
                _context.Add(topics);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(topics);
        }

        // GET: Topics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topics = await _context.Topics.FindAsync(id);
            if (topics == null)
            {
                return NotFound();
            }
            return View(topics);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Topics topics)
        {
            if (id != topics.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(topics);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicsExists(topics.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topics);
        }

        // GET: Topics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topics = await _context.Topics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topics == null)
            {
                return NotFound();
            }

            return View(topics);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)                                          // УДАЛЕНИЕ РАБОТАЕТ!
        {
            foreach (var idishnik in _context.Posters.Where(b => b.TopicId == id).ToList()) {

                var ide = _context.Posters.Where(b => b.TopicId == id).FirstOrDefault().Id;
                var poster = await _context.Posters.FindAsync(ide);

                _context.Posters.Remove(poster);

                await _context.SaveChangesAsync();
            }

            var topics = await _context.Topics.FindAsync(id);
            _context.Topics.Remove(topics);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TopicsExists(int id)
        {
            return _context.Topics.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Магазин Infinity Posters</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="SHORTCUT ICON" href="https://infinityposters.s3.eu-north-1.amazonaws.com/Posters/Design/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Neucha&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spartan:700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pangolin&display=swap" rel="stylesheet">
    <style>
        .a85 {
            width: 100%;
        }

        .ima {
            width: 6vw;
            margin-right: 0.5vw;
        }

        .shops {
            font-size: 1.5vw;
            text-align: center;
            margin-top: 2.5vw;
            text-overflow: clip;
            font-family: 'Pangolin', cursive;
            margin-right: 5vw;
            margin-left: 13vw;
            color: darkblue;
        }
    </style>
</head>
<body>
    <header>
        <nav class=" navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3"  style="background-color: #F7FAA0">
            <div class="container" style="display: flex">
                <a class="ima" asp-controller="Topics" asp-action="Index">
                    <img src="https://infinityposters.s3.eu-north-1.amazonaws.com/Posters/Design/2.png"
                     alt="Infinity Posters" class="a85" title="На главную"
                     style="border-radius: 50%; margin-bottom: 10px; margin-top: 10px"/>
                </a>

                <div style="width: 30%">
                    <a class="navbar-brand" asp-area="" asp-controller="Topics" asp-action="Index"
                        style= "        font-family: 'Neucha', cursive;
        /*font-size: 310%;*/
        font-size: 3.1vw;
        text-align: center;
        margin-top: 1vw;
        text-overflow: clip">
                       Infinity Posters</a>
                </div>

                <a asp-controller="Shops" asp-action="Index" class="shops">Наши магазины</a>
                <a href="https://www.instagram.com/infinity.posters/" target="_blank" title="Наш Instagram"><img src="https://infinityposters.s3.eu-north-1.amazonaws.com/Posters/Design/Instagram_icon.png" alt="Instagram" style="width: 3.7vw; margin-top: 1.6vw; margin-right: 1vw"/></a>
                <div style="        font-family: 'Spartan', sans-serif; font-size: 1vw; margin-top: 2.1vw">
                    +38(095)373-45-93<br />
                    +38(093)412-68-59
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer" style="background-color: rgba(24, 51, 67, 0.99)">
        <div class="container" style="color: white">
            &copy; 2020 - Infinity Posters - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: cornflowerblue">Политика конфиденциальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>